[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"

[compat]
Distributions = "0.25"
Documenter = "0.26, 0.27"
Literate = "2.8"
OptimalTransport = "0.3"
julia = "1"
