[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"

[compat]
Documenter = "0.26"
Literate = "2.8"
OptimalTransport = "0.3, 0.2"
julia = "1"
